# Documentation: http://docs.travis-ci.com/user/languages/c/
language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install python3; else brew install python3; fi
script:
  - make
  - env python3 ./podds-test.py
notifications:
  email: false
